### ISSUE TITLE
not working on iOS 7.

### ISSUE THREAD

**Issue by 0xWDG** [YuAo/WUTextSuggestion#2]
the WUTextSuggestion is not working under iOS 7,
under iOS 6 as you type you get ex. "@an" and it has a autocomplete to "@anna".
in iOS 7, i see only "Select" and "Select all".

**Comment by YuAo** [comment]
Which iOS 7 beta version are you using? It works well on iOS 7 beta 5.

**Comment by link82** [comment]
Same issue for me, it shows the generic tooltip with Select | Select All etc. text

**Comment by YuAo** [comment]
@link82 on iOS 7? Have you tried the demo app.

**Comment by link82** [comment]
Yes, I tried on iOS 7 but not using your demo: inside my application.

In the next days i'll try your demo on my device and let you know.
